version:
  "3"
services:
    zytempmqtt:
        container_name: zigbee2mqtt
        build: ./zytemp_mqtt
        restart: unless-stopped
        volumes:
          - /dev/bus/usb:/dev/bus/usb          # usbfs tree, so libusb can find 04d9:a052
          - ./config.yaml:/root/.config/zytempmqtt/config.yaml:ro
            #    device_cgroup_rules:
            #      - 'c 189:* rmw'                       # 189 = usb character devices
